version: "3.8"

services:
  cloudflare-tunnel:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

  web:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
    # ports:
    #   - "8501:8501"
